name: Ursula Reynolds
favicon: null
layout_spectrum: 0
typography_spectrum: 0.14247786300256848
title: Nonprofit and Small Business Marketing
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#eb0f5e'
    - '#b89d96'
    - '#866532'
    - '#300f9c'
  brandStrength: 0.5571540633682162
  lightness: 0.7350603912491351
  saturation: 0.6579673388041556
  rhythmicContrast: 0.0894719222560525
purpose: []
